"""
conftest.py — shared pytest fixtures for the generated project.
Auto-generated by Forge QAAgent. All imports are guarded so
tests can be collected even before implementation files exist.
Tier 4 — includes JWT auth_token and admin_token fixtures.
"""
from __future__ import annotations
import pytest

# ── HTTP test client ─────────────────────────────────────────────────
try:
    from app.main import app
    from starlette.testclient import TestClient
    _HAS_APP = True
except Exception:
    _HAS_APP = False


@pytest.fixture(scope="module")
def client():
    """TestClient for the FastAPI app."""
    if not _HAS_APP:
        pytest.skip("app not yet implemented")
    with TestClient(app) as c:
        yield c

# ── SQLAlchemy in-memory DB ──────────────────────────────────────────
try:
    from app.database import Base
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker
    _HAS_DB = True
except Exception:
    _HAS_DB = False


@pytest.fixture()
def db():
    """Isolated in-memory SQLite session, reset per test."""
    if not _HAS_DB:
        pytest.skip("database not yet implemented")
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
    )
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    try:
        yield session
    finally:
        session.close()
        Base.metadata.drop_all(engine)


@pytest.fixture()
def session(db):
    """Alias for the db fixture."""
    return db

# ── Auth helpers ─────────────────────────────────────────────────────
try:
    from jose import jwt as _jwt
    import os as _os
    _SECRET = _os.getenv("SECRET_KEY", "test-secret-key")
    _ALGORITHM = "HS256"
    _HAS_JWT = True
except Exception:
    _HAS_JWT = False


@pytest.fixture()
def auth_token():
    """Valid JWT bearer token for role=user."""
    if not _HAS_JWT:
        pytest.skip("jose not installed")
    from datetime import datetime, timedelta
    payload = {
        "sub": "testuser",
        "role": "user",
        "exp": datetime.utcnow() + timedelta(hours=1),
    }
    return _jwt.encode(payload, _SECRET, algorithm=_ALGORITHM)


@pytest.fixture()
def admin_token():
    """Valid JWT bearer token for role=admin."""
    if not _HAS_JWT:
        pytest.skip("jose not installed")
    from datetime import datetime, timedelta
    payload = {
        "sub": "adminuser",
        "role": "admin",
        "exp": datetime.utcnow() + timedelta(hours=1),
    }
    return _jwt.encode(payload, _SECRET, algorithm=_ALGORITHM)
